"""Create editor tables properly

Revision ID: cb9980f62ff0
Revises: e13097151217
Create Date: 2025-12-18 19:34:17.414915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cb9980f62ff0'
down_revision: Union[str, Sequence[str], None] = 'e13097151217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_edits_id'), table_name='video_edits')
    op.drop_table('video_edits')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('duration', sa.FLOAT(), nullable=True),
    sa.Column('resolution', sa.VARCHAR(length=50), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('format', sa.VARCHAR(length=10), nullable=True),
    sa.Column('analysis', sqlite.JSON(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('scenes', sqlite.JSON(), nullable=True),
    sa.Column('transcript', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('video_id', sa.INTEGER(), nullable=True),
    sa.Column('settings', sqlite.JSON(), nullable=True),
    sa.Column('timeline', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('video_edits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('video_id', sa.INTEGER(), nullable=True),
    sa.Column('instruction', sa.TEXT(), nullable=False),
    sa.Column('edit_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('start_time', sa.FLOAT(), nullable=True),
    sa.Column('end_time', sa.FLOAT(), nullable=True),
    sa.Column('duration', sa.FLOAT(), nullable=True),
    sa.Column('generated_content', sqlite.JSON(), nullable=True),
    sa.Column('output_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('progress', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_edits_id'), 'video_edits', ['id'], unique=False)
    # ### end Alembic commands ###
